apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbserver
  template:
    metadata:
      labels:
        app: dbserver
    spec:
      containers:
      - name: dbserver
        image: mysql:8.0.39
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
          name: db-port
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: dbRootPasswd
              name: dbsecret
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: dbUserPasswd
              name: dbsecret
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              key: dbname
              name: backend-cm
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              key: dbuser
              name: backend-cm
